### ISSUE TITLE
Fehler beim Exportieren nach ANNIS 

### ISSUE THREAD

**Issue by Annotation-123** [infraling/atomic#31]
1.	Das Exportieren nach RelANNIS funktionieren bei mir nicht. Der Exporter läuft immer weiter – ohne Ergebnis. 

2.	Bei Exporten von Syntax-Bäumen nach PAULA tritt bei mir folgender Fehler auf:
Im struct-Dokument werden die untergeordneten Relationen falsch ausgegeben. Sie enthalten nach dem id-Wert und den Anführungszeichen noch weitere Anführungszeichen (1x zu viel).

          struct id="structure1">
          rel id="sDomRel1" " xlink:href="nolayer.corpus_document.tok.xml#sTok4"/>
          rel id="sDomRel2" " xlink:href="nolayer.corpus_document.tok.xml#sTok3"/>
          /struct>

3.	Ich habe die überflüssigen Anführungszeichen entfernt und habe PAULA mit saltnpepper dann nach ReLANNIS konvertiert. In ANNIS wurden dann aber die Bezeichnungen der Knoten nicht angezeigt.

**Comment by sdruskat** [comment]
Das Release von 0.1.9 verzögert sich leider noch ein wenig.

**Comment by Annotation-123** [comment]
Und ist absehbar, wann es veröffentlicht wird?

**Comment by sdruskat** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Innerhalb der nächsten 14 Tage sollte die Implementierung
abgeschlossen sein.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJUrQHQAAoJEOa63YqBeAN2wyIH/3rM+HP1WkCnAxBsxewxD3gv
xd1XoMMVSCKkHTawfxffeCv1pXED18qdsMKjr1pDPKOgHRKSNnwLDq1KHEmVBTvz
yZjtcRCwNIljlZQ46w11gtRo/ifB2e+62Gb7DTx8vABWlFkoZSw+kO3kGWvJ0NLU
0MTdmsm3mDIdQ99zNTpKTMgjzyj260ZIav1Q5I7Bq6d7TamWAyPzFd4g1lPjJDbq
uVxZRZtNI+1B8hQJbW31QESnT8Yqe6iHDdaQUFw9JfZNoYujE8iDQj9zxfzMZT6f
XXLDB08KEKxNSWNcdkN1IZqJgLXEuSMWoiBVzTPz4cWsefkQ35mYFUASZ5qZJXM=
=Oa3c
-----END PGP SIGNATURE-----

**Comment by sdruskat** [comment]
Ich wechsle zu Englisch wegen späterer Nachvollziehbarkeit.

This is fixed in 0.1.9, albeit not in its final form (optional STYPE enforcement and a sanity check during export to RelANNIS will be part of a broader update later on, no schedule yet as there are some essential implementations in the pipeline before).

*STYPE*s can now be set on all relation types (ANNIS needs them on *PointingRelation*s and *OrderRelation*s). In order to define an *STYPE* for a relation, simply annotate it with `t:{type of choice}`. This works for annotation directly in the Annotation Graph Editor as well as in AtomicAL.

Note that `t` is a reserved key, i.e., an annotation key that is pre-defined in Atomic. However, in case it collides with the tagset in use, you can re-define it. This can be done application-wide via the respective preferences page (*Options > Preferences > Atomic > Annotation > Reserved keys*). This application-wide preference can also be overridden on a per-project-basis. In order to do so, right-click on a project, and select *Properties* (or press ALT + Enter). On the *Reserved keys* page, select to *Use custom project settings* and re-define the key.

A relation's *STYPE* will be shown next to the relation ID, separated from it with a colon.

**Comment by sdruskat** [comment]
Off-topic and obsolete comments have been deleted for reasons of legibility.
