### ISSUE TITLE
The documentation is inaccessible

### ISSUE THREAD

**Issue by lddubeau** [infraling/atomic#53]
### Steps to reproduce

1. Go to http://corpus-tools.org/atomic/index.html#documentation.

2. Click on the link for the HTML guide (which points to http://linktype.iaa.uni-jena.de/atomic/download/doc/html5/index.xhtml).

### Expected Results

The HTML documentation should load.

### Actual Results

The load times out.

### Observations

The PDF and Epub links also time out. I notice the links all point to `linktype.iaa.uni-jena.de`. Is the site just down? Or should the links be updated to locations on `corpus-tools.org`?

**Comment by sdruskat** [comment]
Thanks for a well-written bug report!

The site at http://linktype.iaa.uni-jena.de/atomic/updates/ is indeed currently down, due to problems with the VM serving it. Critical Atomic infrastructure, such as the update site and documentation, will be moved to a more stable infrastructure in the next couple of days.

**Comment by sdruskat** [comment]
Note: The full user docs are also available from within Atomic via the menu path **Help** > **Help Contents**.
